### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liamxg** [mathii/gdc#6]
Dear @mathii,

please see below:
python3.12 eigenstrat2vcf.py -r humandna
Traceback (most recent call last):
  File "/Volumes/WD_BLACK/AADR/1/eigenstrat2vcf.py", line 7, in <module>
    import argparse, gdc, pyEigenstrat
ModuleNotFoundError: No module named 'pyEigenstrat'

**Comment by mathii** [comment]
Yes you need the pyEigesnstrat package here: https://github.com/mathii/pyEigenstrat

But both that package and this one need python2 (2.7+ probably) not python3.

**Comment by liamxg** [comment]
Dear @mathii,

thanks. but still not work:

```
pip install gdc
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting gdc
  Downloading gdc-1.3.tar.gz (42 kB)
     |████████████████████████████████| 42 kB 630 kB/s 
Requirement already satisfied: cycler==0.10.0 in /Users/lixingguang/opt/miniconda3/envs/py27/lib/python2.7/site-packages (from gdc) (0.10.0)
Requirement already satisfied: kiwisolver==1.1.0 in /Users/lixingguang/opt/miniconda3/envs/py27/lib/python2.7/site-packages (from gdc) (1.1.0)
ERROR: Could not find a version that satisfies the requirement matplotlib==3.1.1 (from gdc) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5)
ERROR: No matching distribution found for matplotlib==3.1.1 (from gdc)
```

**Comment by mathii** [comment]
you are trying to install some other random package named gdc. These scripts do not need to be installed - just run them directly

**Comment by liamxg** [comment]
Hi @mathii,

please see below:

```
python2.7 eigenstrat2vcf.py -r dna
Traceback (most recent call last):
  File "eigenstrat2vcf.py", line 7, in <module>
    import argparse, gdc, pyEigenstrat
ImportError: No module named gdc
```

**Comment by liamxg** [comment]
I can not run them directly, as it prints: `ImportError: No module named gdc`.

**Comment by mathii** [comment]
as long as the script gdc.py is in the same directory as the script you are trying to run, it should work.

**Comment by liamxg** [comment]
Dear @mathii,
still not work:

```
python2.7 eigenstrat2vcf.py -r dna
Traceback (most recent call last):
  File "eigenstrat2vcf.py", line 7, in <module>
    import argparse, gdc, pyEigenstrat
ImportError: No module named pyEigenstrat
```

**Comment by mathii** [comment]
as I already told you, you need to install that package from here: https://github.com/mathii/pyEigenstrat

**Comment by liamxg** [comment]
Dear @mathii,

Thanks. 

but still have issue:

```
python2.7 eigenstrat2vcf.py -r dna
Traceback (most recent call last):
  File "eigenstrat2vcf.py", line 65, in <module>
    main(options)
  File "eigenstrat2vcf.py", line 45, in main
    data=pyEigenstrat.load(options.root, inds=inds, pops=pops, snps=snps)
AttributeError: 'module' object has no attribute 'load'
```

**Comment by mathii** [comment]
Did you actually install the pyEigenstrat module or did you just copy the files into the directory you are running from?

**Comment by liamxg** [comment]
Hi,
I just copy the files in the directory where I am running from, not find the command to install it.

**Comment by mathii** [comment]
as I told you already, you need to install it. 

try 
> git clone git@github.com:mathii/pyEigenstrat.git
> cd pyEigenstrat
> pip install .

or something like that. If you continue to have problems you should ask for help with someone who is more familiar with python.

**Comment by liamxg** [comment]
Dear @mathii,

Thanks now it is installed.

```
pip install .
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /Volumes/WD_BLACK/AADR/1/gdc/pyEigenstrat
Building wheels for collected packages: pyEigenstrat
  Building wheel for pyEigenstrat (setup.py) ... done
  Created wheel for pyEigenstrat: filename=pyEigenstrat-0.0-py2-none-any.whl size=4328 sha256=0937e2106212704b98f7b173299d18e7060d1a38e7b18565c62ee67898155cb0
  Stored in directory: /private/var/folders/q4/gvrdsnj94vl527nfhj25rxh40000gn/T/pip-ephem-wheel-cache-7UpwOw/wheels/81/b6/a1/f4bda3d10c03b7b77dd746074a508bf3fcc69d5950cd1ae4ac
Successfully built pyEigenstrat
Installing collected packages: pyEigenstrat
Successfully installed pyEigenstrat-0.0
```

**Comment by liamxg** [comment]
but When I run the code, it still has error:

```
python2.7 eigenstrat2vcf.py -r dna
Traceback (most recent call last):
  File "eigenstrat2vcf.py", line 65, in <module>
    main(options)
  File "eigenstrat2vcf.py", line 45, in main
    data=pyEigenstrat.load(options.root, inds=inds, pops=pops, snps=snps)
AttributeError: 'module' object has no attribute 'load'

```

**Comment by mathii** [comment]
delete the file eigenstrat2vcf.py from the directory you are running in.  If you continue to have problems you should ask for help with someone who is more familiar with python.
